# Generated by Django 6.0.1 on 2026-01-26 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=50)),
                ('make_company', models.CharField(max_length=50)),
                ('composition', models.CharField(max_length=250)),
                ('make_year', models.DateField()),
                ('limit_year', models.DateField()),
                ('desc', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
